# -*- coding: utf-8 -*-
"""초콜릿 데이터

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WDPadFELC8W6tTl6lBv9YLr2TDmOKX7

1. csv를 읽어 배열로 반환하는 넘파이의 loadtxt() 함수를 사용하고 delimiter 인자로 데이터를 읽어올 때 구분 기호를 콤마(,)로 설정한다.
2. 슬라이싱한 넘파이 배열에 통계함수 mean()을 사용하여모든 초콜릿의 평균 평점을 알아보기.
3. 평점이 4 이상인 우수 초콜릿의 번호를 정수로 변환하여 high_level로 저장한다.
4. 우수 초콜릿의 카카오 함유량을 분석합니다. 넘파이의 unique() 함수는 배열에서 중복 값을 제거하여 남은 값의 배열과 빈도수를 반환합니다.
5. 우수 초콜릿 중 가장 빈도수가 큰 카카오 함유량을 구한다.
"""

import numpy as np
import matplotlib.pyplot as plt
#<1번> loadtxt() 함수로 데이터 읽어오기
#<1번> delimiter를 콤마로 설정
#시각화 - 평점 그래프로 출력
arr = np.loadtxt("/content/chocolate_rating.csv", delimiter=",")
plt.plot(arr[:,3])
plt.show()

print("차원: {}" .format(arr.ndim))
print(f"[{arr}]")

#<2번> mean함수로 평균 평점 구하기
np.mean(arr[:,3])

#<3번> 조건을 주어 평점이 4점 이상인 초콜릿의 번호 high_level에 저장
arr_mask = arr[:,3] >= 4
high_level = arr[arr_mask, 0].astype(int)
num = high_level.size
print(f"우수 초콜릿 수: {num}")
print(high_level)

#<4번> unique함수로 함유량과 빈도수 파악
unique_arr, counts = np.unique(arr[high_level-1, 2], return_counts = True)
plt.stem(unique_arr, counts)
plt.show()

print("카카오 함유량: ", unique_arr)
print("함유량별 빈도수: ", counts)

#<5번> 우수 초콜렛 중 가장 많은 빈도수를 가진 것의 함유량 출력
max = np.argmax(counts)
result = int(unique_arr[max]*100)
print(f"우수 초콜릿 {num}가지 중 45가지의 카카오 함유량이 {result}%입니다." )